
// This file has been generated by the GUI designer. Do not modify.
namespace HelloBulb
{
	public partial class DimmerWindow
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.SpinButton spinbutton1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.SpinButton spinbutton2;
		
		private global::Gtk.Button button3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget HelloBulb.DimmerWindow
			this.Name = "HelloBulb.DimmerWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("DimmerWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child HelloBulb.DimmerWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Moc maksymalna żarówki(min. 15, max. 1000)");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w1.X = 10;
			w1.Y = 11;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.spinbutton1 = new global::Gtk.SpinButton (15D, 1000D, 1D);
			this.spinbutton1.CanFocus = true;
			this.spinbutton1.Name = "spinbutton1";
			this.spinbutton1.Adjustment.PageIncrement = 10D;
			this.spinbutton1.ClimbRate = 1D;
			this.spinbutton1.Numeric = true;
			this.spinbutton1.Value = 250D;
			this.fixed1.Add (this.spinbutton1);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.spinbutton1]));
			w2.X = 320;
			w2.Y = 8;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Moc minimalna zarówki (min. 0, max. 14)");
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w3.X = 12;
			w3.Y = 48;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.spinbutton2 = new global::Gtk.SpinButton (0D, 14D, 1D);
			this.spinbutton2.CanFocus = true;
			this.spinbutton2.Name = "spinbutton2";
			this.spinbutton2.Adjustment.PageIncrement = 10D;
			this.spinbutton2.ClimbRate = 1D;
			this.spinbutton2.Numeric = true;
			this.fixed1.Add (this.spinbutton2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.spinbutton2]));
			w4.X = 320;
			w4.Y = 43;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("Zamknij");
			this.fixed1.Add (this.button3);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button3]));
			w5.X = 161;
			w5.Y = 92;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 158;
			this.Show ();
			this.spinbutton1.ValueChanged += new global::System.EventHandler (this.zmin);
			this.spinbutton2.ValueChanged += new global::System.EventHandler (this.zmin1);
		}
	}
}
