
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action homeAction;
	
	private global::Gtk.Action okAction;
	
	private global::Gtk.Action dialogInfoAction1;
	
	private global::Gtk.Action cancelAction;
	
	private global::Gtk.Action propertiesAction;
	
	private global::Gtk.Action AboutAction1;
	
	private global::Gtk.Action dialogInfoAction;
	
	private global::Gtk.Action dialogErrorAction;
	
	private global::Gtk.Fixed fixed2;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.Image image1;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.HScrollbar hscrollbar1;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.SpinButton spinbuttonDimmer;
	
	private global::Gtk.Button buttonOFF;
	
	private global::Gtk.Button buttonON;
	
	private global::Gtk.ToggleButton togglebutton1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.homeAction = new global::Gtk.Action ("homeAction", global::Mono.Unix.Catalog.GetString ("Menu"), null, "gtk-home");
		this.homeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Bulb!");
		w1.Add (this.homeAction, null);
		this.okAction = new global::Gtk.Action ("okAction", global::Mono.Unix.Catalog.GetString ("Zapal"), null, "gtk-ok");
		this.okAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("ON");
		w1.Add (this.okAction, null);
		this.dialogInfoAction1 = new global::Gtk.Action ("dialogInfoAction1", global::Mono.Unix.Catalog.GetString ("Informacje"), null, "gtk-dialog-info");
		this.dialogInfoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("About...");
		w1.Add (this.dialogInfoAction1, null);
		this.cancelAction = new global::Gtk.Action ("cancelAction", global::Mono.Unix.Catalog.GetString ("Zgaś"), null, "gtk-cancel");
		this.cancelAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("OFF");
		w1.Add (this.cancelAction, null);
		this.propertiesAction = new global::Gtk.Action ("propertiesAction", global::Mono.Unix.Catalog.GetString ("Dimm Options"), null, "gtk-properties");
		this.propertiesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Dimm");
		w1.Add (this.propertiesAction, null);
		this.AboutAction1 = new global::Gtk.Action ("AboutAction1", global::Mono.Unix.Catalog.GetString ("About..."), null, null);
		this.AboutAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("About...");
		w1.Add (this.AboutAction1, null);
		this.dialogInfoAction = new global::Gtk.Action ("dialogInfoAction", global::Mono.Unix.Catalog.GetString ("Informacje o aplikacji"), null, "gtk-dialog-info");
		this.dialogInfoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About...");
		w1.Add (this.dialogInfoAction, null);
		this.dialogErrorAction = new global::Gtk.Action ("dialogErrorAction", global::Mono.Unix.Catalog.GetString ("Zamknij"), null, "gtk-dialog-error");
		this.dialogErrorAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Zamknij");
		w1.Add (this.dialogErrorAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 500;
		this.DefaultHeight = 500;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString (@"<ui><menubar name='menubar1'><menu name='homeAction' action='homeAction'><menuitem name='okAction' action='okAction'/><menuitem name='cancelAction' action='cancelAction'/><menuitem name='propertiesAction' action='propertiesAction'/></menu><menu name='dialogInfoAction1' action='dialogInfoAction1'><menuitem name='dialogInfoAction' action='dialogInfoAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.fixed2.Add (this.menubar1);
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.image1 = new global::Gtk.Image ();
		this.image1.WidthRequest = 600;
		this.image1.HeightRequest = 600;
		this.image1.Name = "image1";
		this.fixed2.Add (this.image1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.image1]));
		w3.X = 1;
		w3.Y = 25;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Skalowanie :");
		this.fixed2.Add (this.label1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label1]));
		w4.X = 14;
		w4.Y = 707;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.hscrollbar1 = new global::Gtk.HScrollbar (null);
		this.hscrollbar1.WidthRequest = 250;
		this.hscrollbar1.Name = "hscrollbar1";
		this.hscrollbar1.Adjustment.Upper = 70D;
		this.hscrollbar1.Adjustment.PageIncrement = 10D;
		this.hscrollbar1.Adjustment.PageSize = 10D;
		this.hscrollbar1.Adjustment.StepIncrement = 1D;
		this.hscrollbar1.Adjustment.Value = 60D;
		this.fixed2.Add (this.hscrollbar1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.hscrollbar1]));
		w5.X = 83;
		w5.Y = 704;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Jasność :");
		this.fixed2.Add (this.label2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label2]));
		w6.X = 33;
		w6.Y = 675;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.spinbuttonDimmer = new global::Gtk.SpinButton (0D, 250D, 1D);
		this.spinbuttonDimmer.CanFocus = true;
		this.spinbuttonDimmer.Name = "spinbuttonDimmer";
		this.spinbuttonDimmer.Adjustment.PageIncrement = 10D;
		this.spinbuttonDimmer.ClimbRate = 1D;
		this.spinbuttonDimmer.Numeric = true;
		this.spinbuttonDimmer.Value = 250D;
		this.fixed2.Add (this.spinbuttonDimmer);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.spinbuttonDimmer]));
		w7.X = 84;
		w7.Y = 672;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.buttonOFF = new global::Gtk.Button ();
		this.buttonOFF.WidthRequest = 80;
		this.buttonOFF.CanFocus = true;
		this.buttonOFF.Name = "buttonOFF";
		this.buttonOFF.UseUnderline = true;
		this.buttonOFF.Label = global::Mono.Unix.Catalog.GetString ("Zgaś");
		this.fixed2.Add (this.buttonOFF);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.buttonOFF]));
		w8.X = 459;
		w8.Y = 698;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.buttonON = new global::Gtk.Button ();
		this.buttonON.WidthRequest = 80;
		this.buttonON.CanFocus = true;
		this.buttonON.Name = "buttonON";
		this.buttonON.UseUnderline = true;
		this.buttonON.Label = global::Mono.Unix.Catalog.GetString ("Zapal");
		this.fixed2.Add (this.buttonON);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.buttonON]));
		w9.X = 459;
		w9.Y = 667;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.togglebutton1 = new global::Gtk.ToggleButton ();
		this.togglebutton1.WidthRequest = 121;
		this.togglebutton1.CanFocus = true;
		this.togglebutton1.Name = "togglebutton1";
		this.togglebutton1.UseUnderline = true;
		this.togglebutton1.Label = global::Mono.Unix.Catalog.GetString ("Przełącz (...)");
		this.fixed2.Add (this.togglebutton1);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.togglebutton1]));
		w10.X = 334;
		w10.Y = 667;
		this.Add (this.fixed2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.okAction.Activated += new global::System.EventHandler (this.bulb_on);
		this.cancelAction.Activated += new global::System.EventHandler (this.bulb_off);
		this.propertiesAction.Activated += new global::System.EventHandler (this.Dimmactive);
		this.dialogInfoAction.Activated += new global::System.EventHandler (this.about);
		this.hscrollbar1.ValueChanged += new global::System.EventHandler (this.res);
		this.spinbuttonDimmer.ValueChanged += new global::System.EventHandler (this.spindim);
		this.togglebutton1.Clicked += new global::System.EventHandler (this.togglebut);
	}
}
